# 1. Import Libraries

In [80]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

# 2. Load data

In [81]:
ratings_df = pd.read_csv(
    "dataset/ratings.dat",
    sep="::",
    engine="python",
    names=["user", "item", "rating", "ts"],
    encoding="latin-1",
)

ratings_df

         user  item  rating         ts
0           1  1193       5  978300760
1           1   661       3  978302109
2           1   914       3  978301968
3           1  3408       4  978300275
4           1  2355       5  978824291
...       ...   ...     ...        ...
1000204  6040  1091       1  956716541
1000205  6040  1094       5  956704887
1000206  6040   562       5  956704746
1000207  6040  1096       4  956715648
1000208  6040  1097       4  956715569

[1000209 rows x 4 columns]

In [82]:
print(ratings_df["user"].nunique())
print(ratings_df["item"].nunique())

6040
3706

In [83]:
movies_df = pd.read_csv(
    "dataset/movies.dat",
    sep="::",
    engine="python",
    names=["item", "title", "genres"],
    encoding="latin-1",
)

movies_df

      item                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
...    ...                                 ...                           ...
3878  3948             Meet the Parents (2000)                        Comedy
3879  3949          Requiem for a Dream (2000)                         Drama
3880  3950                    Tigerland (2000)                         Drama
3881  3951             Two Family House (2000)                         Drama
3882  3952               Contender, The (2000)                Drama|Thriller

[3883 rows x 3 columns]

In [84]:
users_df = pd.read_csv(
    "dataset/users.dat",
    sep="::",
    engine="python",
    names=["user", "gender", "age", "occupation", "zip"],
    encoding="latin-1",
)

users_df

      user gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455
...    ...    ...  ...         ...    ...
6035  6036      F   25          15  32603
6036  6037      F   45           1  76006
6037  6038      F   56           1  14706
6038  6039      F   45           0  01060
6039  6040      M   25           6  11106

[6040 rows x 5 columns]

# 3. Data preparation

## 3.1 Filter out movies that have less than 5 ratings, as well as users who rate less than 5 times

In [85]:
print(ratings_df["user"].value_counts().min())
print(ratings_df["item"].value_counts().min())

20
1

In [86]:
counts = ratings_df["item"].value_counts()

filtered_movies_list = counts[counts >= 5].index.tolist()

print(filtered_movies_list)

[2858, 260, 1196, 1210, 480, 2028, 589, 2571, 1270, 593, 1580, 1198, 608, 2762, 110, 2396, 1197, 527, 1617, 1265, 1097, 2628, 2997, 318, 858, 356, 2716, 296, 1240, 1, 1214, 2916, 457, 3578, 1200, 541, 2987, 1259, 50, 34, 2791, 780, 3175, 1193, 919, 924, 1127, 2355, 1387, 1221, 912, 1036, 1213, 1610, 377, 1291, 2000, 1136, 3114, 1307, 1704, 1721, 1968, 648, 2599, 3793, 32, 2174, 2797, 2291, 2918, 590, 3471, 2959, 1374, 2683, 1394, 592, 1784, 1573, 1304, 3418, 223, 380, 2706, 1225, 1584, 1527, 3481, 1923, 2699, 750, 39, 21, 1393, 2804, 588, 2406, 1220, 733, 1230, 3176, 1961, 3751, 1079, 908, 3408, 1073, 3623, 1356, 3527, 2700, 1219, 1247, 1089, 1544, 1222, 150, 3753, 111, 2710, 2657, 357, 1094, 2985, 1206, 3147, 2640, 2395, 3421, 1517, 1641, 1278, 1252, 367, 1358, 1208, 2100, 1676, 2529, 2321, 2011, 920, 2324, 2012, 1090, 47, 1500, 1370, 1954, 1673, 2194, 2115, 1376, 587, 364, 3253, 3671, 1288, 923, 316, 3160, 1242, 1917, 736, 3255, 1294, 1732, 3361, 1396, 2763, 1258, 2302, 3448, 1653, 1608, 1391, 2692, 2455, 3702, 3081, 2268, 595, 349, 969, 3256, 904, 1234, 597, 1674, 2054, 913, 2081, 3703, 11, 1377, 2890, 3755, 2001, 1028, 2968, 1101, 2617, 2407, 1682, 1233, 1372, 1266, 1909, 551, 3897, 3363, 329, 1183, 3052, 2353, 539, 2006, 3072, 25, 2289, 1408, 474, 2105, 3552, 1639, 1552, 440, 788, 3108, 2712, 1215, 1282, 6, 2336, 1250, 2746, 2770, 1276, 1207, 36, 235, 1375, 1080, 1320, 293, 70, 2248, 1199, 2470, 1777, 1912, 3555, 1747, 903, 2701, 3033, 2947, 1876, 10, 1407, 3210, 1997, 1179, 3006, 3499, 1129, 1625, 1035, 1148, 1748, 3174, 2502, 3107, 3699, 2080, 3082, 1722, 3948, 1953, 3608, 1246, 2723, 2915, 2908, 2641, 2369, 3039, 3543, 500, 2424, 2352, 17, 910, 1204, 1645, 2108, 165, 454, 1201, 3510, 1569, 1380, 3809, 1597, 3526, 3450, 2167, 2393, 2278, 1285, 2427, 2193, 2002, 3101, 368, 2058, 2064, 1994, 3354, 1371, 2694, 3624, 2243, 2021, 1060, 2881, 3424, 2671, 1690, 2605, 153, 2003, 2023, 2020, 2490, 265, 2948, 1302, 344, 785, 3104, 1267, 3362, 594, 1947, 161, 3386, 2366, 1513, 778, 899, 1092, 1965, 2826, 1231, 2391, 1077, 3396, 2872, 1275, 2288, 1663, 253, 2094, 353, 1249, 292, 1333, 1299, 3698, 2871, 953, 1729, 2580, 3704, 3489, 529, 1466, 2144, 1244, 246, 2005, 968, 2124, 2160, 3148, 2140, 2944, 266, 300, 1287, 2359, 2, 3763, 288, 2572, 1263, 2161, 1235, 1262, 2150, 337, 2145, 3868, 2688, 3504, 1088, 1343, 1084, 434, 104, 543, 141, 16, 1093, 3105, 708, 1228, 902, 1188, 586, 2761, 2405, 339, 1339, 1269, 1293, 1918, 3476, 497, 1831, 3263, 3247, 1485, 2078, 1883, 1952, 231, 555, 3863, 2300, 745, 3911, 2076, 1962, 3638, 208, 2724, 2949, 2294, 1272, 441, 3697, 317, 442, 2329, 3005, 95, 914, 1960, 2527, 2707, 1957, 800, 3535, 3591, 2019, 2664, 3683, 1711, 2273, 2528, 1959, 3257, 1805, 2542, 24, 2581, 2616, 3100, 2013, 610, 1203, 2539, 1172, 852, 1037, 3785, 1373, 1921, 2433, 653, 3070, 1885, 509, 1562, 198, 3301, 471, 2371, 2722, 1256, 2087, 1271, 1292, 3037, 3360, 3298, 2018, 2501, 3717, 3740, 3044, 2686, 898, 2394, 2333, 3273, 1022, 1019, 466, 2109, 866, 1587, 1095, 112, 2478, 185, 1029, 1345, 160, 2662, 2085, 2717, 832, 173, 2067, 3113, 1479, 673, 1186, 1378, 508, 1296, 3752, 3893, 1253, 2541, 3060, 2792, 1586, 2976, 3252, 151, 1967, 553, 3435, 196, 2795, 1321, 3098, 1261, 1357, 3685, 45, 3300, 3479, 3614, 1779, 62, 1284, 2133, 163, 2046, 3745, 3438, 3524, 435, 2598, 1958, 552, 1042, 1911, 661, 1032, 3020, 2384, 2951, 3095, 3157, 3359, 1945, 342, 2863, 3087, 2423, 350, 1248, 2245, 2428, 3264, 2642, 849, 2096, 2134, 3178, 1956, 1635, 2469, 1982, 3534, 2917, 3701, 3654, 58, 838, 485, 1882, 1476, 596, 1590, 3203, 2137, 3317, 3735, 2126, 2986, 1834, 2420, 1589, 162, 1907, 3536, 3635, 2841, 3168, 628, 3173, 1104, 3267, 2186, 1441, 2454, 3260, 1212, 1059, 2065, 3, 562, 3827, 3269, 2421, 247, 524, 2719, 1405, 1644, 3246, 2463, 1591, 3441, 1678, 1041, 2431, 2912, 1223, 1257, 1694, 2088, 1894, 922, 2311, 1566, 345, 2734, 1680, 2533, 410, 3798, 1449, 1385, 3639, 3334, 786, 2973, 2735, 3409, 7, 172, 2313, 671, 1120, 348, 1717, 3512, 1185, 3730, 1254, 3159, 1274, 1955, 1049, 1347, 180, 2788, 3468, 2739, 515, 994, 1792, 3706, 2805, 3016, 3219, 3358, 2409, 930, 2926, 3545, 2413, 933, 1297, 2687, 647, 2253, 2116, 3274, 720, 3916, 379, 3791, 1081, 2450, 1047, 3254, 144, 3186, 52, 3869, 2759, 3261, 2966, 372, 1614, 802, 2728, 1224, 2989, 916, 3285, 2991, 2009, 3035, 2713, 3744, 3513, 2335, 1100, 2840, 3617, 303, 585, 2375, 909, 748, 724, 494, 2125, 3019, 2622, 1171, 2471, 3686, 2378, 955, 370, 333, 2485, 2600, 1350, 3844, 1135, 2648, 3826, 1124, 2993, 2141, 1283, 29, 3259, 926, 1103, 2402, 1892, 2410, 3551, 1499, 2857, 3185, 951, 2403, 1616, 1620, 2702, 3196, 3083, 1020, 1409, 432, 1801, 2672, 2919, 2690, 783, 532, 3507, 19, 3952, 2010, 1754, 1298, 1888, 105, 674, 224, 2334, 928, 784, 2990, 2794, 1125, 2718, 272, 954, 3156, 48, 517, 1411, 2053, 1719, 2398, 3705, 2015, 1459, 3068, 1086, 164, 2414, 22, 940, 2411, 3836, 2808, 1061, 520, 2468, 905, 1091, 1301, 2720, 2565, 1078, 1914, 2004, 2301, 1388, 2139, 1379, 3618, 431, 1175, 1556, 252, 2110, 1835, 3250, 2247, 2530, 915, 3712, 3508, 1944, 1920, 1367, 1277, 2118, 1619, 145, 168, 2942, 1344, 2082, 3525, 2496, 3811, 3201, 3684, 3397, 327, 1245, 2532, 60, 1217, 2747, 3088, 3668, 216, 2143, 2297, 1327, 3505, 1518, 2416, 3152, 2861, 1916, 3067, 3633, 3461, 1810, 420, 2146, 3062, 1238, 1693, 546, 3451, 376, 1537, 468, 230, 1603, 1950, 3927, 2112, 232, 514, 2803, 2950, 2231, 2779, 3000, 3615, 1096, 1027, 2340, 805, 2474, 900, 3034, 3593, 3053, 2953, 3398, 2995, 3249, 3258, 3688, 799, 1334, 3770, 531, 1687, 492, 306, 3155, 2643, 3452, 2312, 2390, 2901, 1300, 222, 2827, 3271, 3556, 3265, 3071, 236, 2262, 2303, 2376, 3681, 1243, 3198, 880, 2467, 1030, 3244, 170, 1672, 1438, 3528, 3494, 2318, 69, 2819, 1769, 1031, 125, 2971, 1126, 1268, 2921, 1974, 2282, 3040, 538, 741, 3328, 2531, 2111, 475, 2401, 44, 1303, 2367, 507, 3146, 1260, 1594, 1895, 2802, 2867, 678, 3841, 911, 3871, 2513, 3462, 2138, 3760, 934, 2130, 3163, 3566, 2348, 3949, 3802, 1688, 1381, 2072, 1964, 921, 2567, 1702, 3484, 2404, 1845, 1012, 535, 2363, 3189, 314, 737, 2476, 2346, 1237, 1884, 493, 3388, 3355, 762, 2132, 1429, 5, 830, 412, 3649, 2034, 3498, 3007, 2338, 1395, 3308, 481, 2518, 3243, 1025, 950, 942, 2946, 1009, 2875, 2322, 1588, 3316, 3733, 2153, 3129, 1488, 2889, 1033, 2422, 999, 534, 3812, 1286, 455, 2750, 261, 3576, 1701, 2456, 1416, 1422, 2613, 2764, 2941, 2287, 2961, 3873, 3917, 3467, 616, 2117, 3565, 1280, 2883, 1147, 1017, 3384, 2093, 3251, 3629, 707, 3061, 1057, 2412, 1969, 3429, 3548, 3099, 861, 319, 2517, 2668, 2505, 382, 2815, 3477, 3675, 3307, 971, 383, 3723, 426, 1189, 952, 3501, 3469, 1970, 1927, 361, 2059, 3238, 355, 1354, 2155, 3708, 2524, 1295, 2447, 3478, 1457, 2676, 1633, 1480, 3366, 1643, 2793, 2070, 2389, 1833, 599, 3208, 663, 2822, 428, 1735, 2083, 1342, 249, 3549, 1873, 2457, 2408, 2188, 158, 3145, 3153, 373, 1013, 351, 1264, 237, 2114, 107, 996, 225, 446, 2022, 101, 965, 3169, 1689, 3089, 1963, 3004, 3197, 366, 3439, 945, 2906, 1627, 1924, 2090, 3821, 3018, 516, 2459, 1021, 3700, 2772, 3788, 3764, 413, 3365, 2121, 3819, 1218, 2374, 3102, 273, 307, 41, 1010, 1971, 1211, 2120, 3741, 1227, 3861, 2922, 1541, 2796, 719, 2249, 2859, 362, 1991, 2089, 1348, 1542, 2240, 2135, 2644, 2372, 3707, 836, 879, 1939, 86, 1611, 2316, 2583, 2558, 3783, 233, 3882, 1015, 3742, 2203, 804, 2122, 281, 2232, 986, 1431, 2709, 3932, 1007, 3213, 1713, 1205, 1130, 2147, 1772, 2677, 1290, 1178, 2745, 89, 450, 1251, 448, 276, 1615, 1762, 3516, 605, 1226, 2279, 3179, 2379, 2736, 1931, 2693, 73, 3032, 3342, 2399, 3930, 3546, 3729, 2136, 1359, 3444, 3074, 338, 42, 2025, 2099, 423, 1023, 2670, 175, 3430, 1132, 1783, 3194, 1949, 1392, 3466, 207, 3814, 2159, 2553, 3404, 1683, 837, 256, 193, 2269, 728, 2387, 1340, 464, 1461, 611, 1131, 1281, 3426, 282, 949, 3030, 2123, 2357, 1973, 2929, 2568, 688, 1799, 3111, 2202, 2097, 194, 2907, 1951, 280, 491, 371, 3347, 1194, 381, 1821, 186, 2877, 1389, 1727, 3394, 3422, 3682, 1191, 322, 1064, 3852, 3093, 417, 537, 2606, 3022, 3928, 3097, 3754, 931, 1752, 2163, 542, 176, 1946, 2392, 3204, 798, 203, 405, 533, 204, 3296, 519, 2236, 308, 3248, 2344, 2259, 1734, 2729, 2142, 3825, 3270, 3910, 1972, 1665, 3125, 2033, 2574, 3420, 3676, 3519, 3801, 2866, 1976, 2107, 2208, 2806, 1753, 2038, 1948, 1862, 1173, 1966, 2439, 2102, 2380, 2171, 477, 3724, 218, 1983, 2266, 3135, 122, 3066, 1099, 85, 1279, 1648, 2473, 2870, 2042, 407, 88, 3515, 3766, 2176, 188, 3324, 3029, 3769, 1760, 1649, 1866, 2551, 2373, 2615, 1446, 2448, 818, 918, 932, 3440, 947, 1353, 3521, 429, 938, 2731, 906, 157, 2320, 2952, 3831, 2252, 2091, 2106, 2891, 2752, 3710, 490, 3786, 2550, 2377, 891, 2060, 374, 2052, 94, 1289, 3693, 3877, 3594, 1995, 147, 2504, 1515, 2014, 2429, 3326, 3646, 3926, 1785, 2520, 1660, 2183, 3598, 28, 415, 2331, 512, 3896, 3268, 504, 3835, 76, 550, 1848, 3500, 3341, 3090, 2162, 3834, 3299, 1730, 482, 3538, 2453, 2263, 1066, 3412, 2549, 574, 1346, 901, 2381, 742, 3036, 3387, 2328, 1209, 3200, 262, 1858, 3272, 2771, 3773, 2560, 1975, 943, 2071, 765, 4, 277, 2497, 1128, 991, 1977, 3606, 1034, 2730, 2546, 540, 154, 239, 3483, 1806, 3177, 290, 1425, 1414, 3918, 2349, 2206, 3506, 1797, 1913, 43, 3167, 427, 81, 2148, 46, 2846, 3784, 3134, 3634, 2789, 2902, 2555, 1083, 1875, 2852, 195, 2879, 2639, 3181, 3262, 2836, 2092, 2506, 2787, 1487, 2017, 2633, 1401, 1593, 332, 3190, 946, 2026, 2261, 3024, 2936, 3051, 2900, 1840, 2943, 3550, 2798, 2442, 215, 3325, 20, 12, 1361, 289, 2043, 1150, 2361, 3392, 18, 2829, 3660, 549, 1445, 2540, 3672, 848, 419, 3789, 1016, 3078, 3480, 3529, 1699, 502, 1707, 2077, 3266, 1082, 315, 2525, 714, 14, 892, 438, 511, 473, 842, 3364, 1794, 3771, 2382, 3011, 2383, 518, 3653, 330, 3747, 3728, 2024, 2816, 1453, 2732, 3727, 2119, 2184, 3929, 2315, 3865, 1187, 1177, 234, 2611, 2432, 2385, 1474, 1273, 15, 1050, 2041, 1503, 782, 3079, 1464, 2935, 700, 1468, 258, 2629, 2166, 2430, 3015, 328, 709, 2296, 3879, 3405, 3503, 3864, 65, 299, 3350, 459, 1863, 1005, 2370, 3457, 2354, 2956, 2575, 581, 31, 3091, 3385, 358, 1483, 436, 3689, 694, 2154, 2475, 637, 378, 2069, 267, 3445, 3028, 2492, 2596, 140, 3063, 177, 3616, 3846, 248, 1554, 2748, 1726, 548, 3054, 1306, 1014, 2554, 2612, 1419, 2365, 558, 695, 1011, 3889, 2195, 839, 2757, 2660, 3937, 1836, 2310, 1681, 3475, 3327, 2654, 2996, 1992, 3206, 479, 2851, 135, 1897, 2924, 556, 936, 1190, 2561, 1085, 1498, 829, 2048, 2526, 2726, 2169, 3142, 2458, 3120, 948, 1985, 2027, 2241, 544, 3287, 3584, 1176, 227, 2151, 1623, 3564, 2212, 3436, 100, 2068, 662, 2860, 2040, 1986, 360, 851, 1382, 3571, 305, 3915, 1999, 2967, 1024, 2337, 1465, 23, 2443, 2817, 2280, 3925, 547, 3182, 1484, 1018, 761, 2498, 213, 2170, 3225, 3690, 3604, 3286, 1938, 2436, 1003, 3794, 691, 627, 2364, 3600, 2290, 1390, 2828, 801, 1305, 74, 3758, 346, 810, 2325, 1804, 2888, 2535, 2500, 352, 1942, 3554, 3130, 2932, 2181, 3045, 2882, 523, 2360, 199, 2899, 521, 3824, 1919, 2460, 1658, 1330, 3557, 2514, 159, 123, 2491, 334, 257, 79, 506, 1978, 1904, 3709, 169, 3401, 2095, 1941, 2451, 1667, 1998, 1996, 1979, 3840, 1592, 1363, 3936, 3725, 312, 2272, 2975, 63, 1598, 2351, 2173, 1069, 3115, 2418, 1629, 2165, 1606, 2016, 1686, 229, 1366, 3330, 2988, 1855, 1043, 575, 2940, 1935, 2782, 2669, 3627, 743, 451, 3807, 692, 3901, 2066, 2548, 1192, 907, 187, 425, 393, 1984, 809, 941, 3406, 465, 3767, 886, 3017, 1824, 2314, 2937, 2050, 3923, 1399, 2149, 781, 1535, 3357, 835, 2978, 3599, 2624, 387, 1332, 9, 2645, 3872, 2898, 2570, 259, 2587, 1827, 1816, 1004, 3643, 3628, 2051, 735, 3094, 1362, 2920, 978, 445, 1758, 3946, 1432, 766, 3799, 569, 26, 190, 2327, 13, 2799, 2927, 1981, 57, 2435, 126, 2970, 1051, 2182, 2495, 3726, 897, 2903, 66, 1993, 2239, 3544, 1008, 489, 3214, 944, 388, 2519, 2036, 3391, 3497, 1162, 3943, 2356, 71, 2347, 3379, 2725, 1841, 2178, 3613, 1352, 1111, 1460, 421, 1167, 2661, 3895, 501, 1161, 606, 2472, 3076, 2084, 3096, 929, 2634, 456, 72, 998, 181, 171, 2330, 3908, 3509, 3275, 3662, 3470, 3619, 2969, 1788, 725, 2801, 1940, 1980, 1184, 1987, 3217, 2807, 2057, 132, 3678, 1647, 1236, 1046, 1410, 2856, 414, 2306, 3837, 2862, 3453, 82, 416, 93, 650, 2204, 3715, 1526, 1646, 2682, 3077, 1605, 3502, 92, 1661, 2714, 2749, 155, 3720, 3399, 458, 3919, 1654, 1216, 461, 302, 3370, 2721, 2437, 3431, 697, 3590, 3046, 2488, 205, 3713, 1621, 1600, 1640, 2521, 340, 1929, 927, 3622, 2264, 2177, 2844, 3813, 2265, 522, 3810, 1936, 613, 3859, 1733, 3055, 1670, 2511, 2651, 2780, 3553, 973, 206, 3661, 1454, 2075, 2696, 3086, 3768, 1054, 2983, 982, 174, 1475, 1626, 1440, 444, 242, 275, 117, 270, 612, 2522, 2255, 64, 3425, 2168, 2738, 2113, 3230, 639, 1006, 833, 3738, 917, 635, 1655, 2928, 1355, 1934, 2238, 3743, 3224, 1744, 3547, 3572, 2769, 881, 2029, 2098, 1404, 87, 2271, 424, 191, 1601, 631, 3038, 30, 2445, 2417, 764, 483, 3423, 2267, 3427, 1642, 2295, 3117, 1545, 3417, 3041, 3432, 3447, 3199, 1202, 1856, 3792, 2786, 1870, 2965, 2880, 408, 2275, 3340, 935, 449, 1550, 3669, 3048, 3235, 3732, 1442, 640, 2665, 365, 2062, 2276, 3180, 3822, 3112, 3914, 1241, 35, 2621, 3746, 2905, 2419, 152, 3075, 469, 893, 988, 3909, 3658, 3858, 505, 2152, 1839, 3487, 8, 3579, 118, 2607, 2774, 528, 1881, 3103, 1599, 2974, 2609, 61, 2874, 513, 615, 354, 609, 453, 3716, 3714, 3920, 3211, 2582, 3511, 2073, 3138, 2625, 3823, 3491, 156, 3795, 255, 3118, 3375, 2649, 3013, 1604, 3042, 2007, 1595, 3456, 3696, 2972, 486, 3109, 3774, 2589, 1337, 217, 680, 437, 1731, 2597, 1456, 1837, 1937, 2781, 1397, 1750, 1482, 1398, 3368, 2784, 3787, 271, 2868, 2446, 2656, 487, 3141, 3310, 3679, 580, 3459, 363, 3514, 2461, 2250, 2594, 1703, 711, 3694, 326, 1943, 3165, 321, 2741, 2790, 2885, 1900, 27, 2283, 565, 166, 3718, 2434, 3857, 3150, 3596, 806, 1887, 102, 68, 1582, 3577, 3064, 3496, 759, 3428, 390, 882, 2386, 1581, 959, 603, 3663, 2818, 2667, 2425, 1684, 3806, 2180, 369, 3692, 2368, 1365, 2035, 3241, 2753, 2925, 803, 1523, 422, 3734, 3833, 2835, 976, 3372, 3304, 670, 1326, 3127, 3947, 747, 269, 2045, 1336, 577, 1746, 536, 1612, 1609, 3395, 3069, 3950, 268, 3664, 1865, 467, 1255, 828, 3518, 2462, 2285, 2210, 2507, 313, 2751, 990, 2037, 3188, 963, 3031, 3302, 1341, 2104, 113, 3695, 2362, 2820, 2663, 1791, 3903, 1922, 3289, 209, 1516, 2190, 1428, 2515, 2499, 2647, 1232, 2044, 715, 2939, 80, 779, 2652, 3008, 1988, 1759, 1869, 3790, 710, 1756, 3416, 3393, 896, 1427, 964, 3605, 3128, 1624, 2733, 1650, 3737, 3655, 1180, 99, 78, 3620, 1413, 1113, 840, 3414, 1056, 1331, 3870, 1889, 3144, 3014, 325, 1447, 182, 3602, 2260, 1631, 1546, 499, 870, 3281, 3626, 409, 2590, 3588, 179, 309, 1497, 2585, 3433, 3318, 433, 1854, 888, 3371, 2697, 291, 2573, 1472, 1771, 2708, 2655, 498, 149, 1896, 3839, 1739, 731, 667, 813, 463, 3680, 668, 3921, 2440, 3674, 2659, 347, 3765, 279, 2812, 3276, 1439, 2618, 3677, 3719, 3284, 55, 2516, 3183, 1571, 240, 3320, 1925, 2977, 564, 3898, 2479, 2341, 472, 1525, 97, 3808, 875, 2614, 3782, 3158, 937, 1495, 2237, 1812, 1860, 1417, 808, 3731, 3849, 3804, 2345, 3945, 885, 1323, 2286, 2876, 3454, 3339, 2400, 301, 2284, 2681, 3367, 1602, 1310, 1798, 3838, 2653, 2523, 343, 294, 621, 3133, 869, 704, 3691, 1507, 2842, 2465, 510, 1105, 2477, 2884, 2893, 495, 2055, 210, 2704, 116, 2848, 2810, 2630, 2610, 54, 3780, 335, 2689, 602, 1910, 384, 956, 3886, 3912, 3884, 987, 3951, 1317, 3043, 278, 3851, 1563, 3739, 1473, 3632, 3343, 1826, 2566, 391, 2032, 1668, 656, 3539, 3446, 3922, 3855, 488, 2179, 2646, 3736, 3442, 3389, 452, 846, 2982, 1867, 3816, 2744, 3132, 254, 3659, 3434, 2307, 470, 460, 1677, 1547, 3239, 2979, 121, 970, 2049, 2536, 1829, 2552, 3049, 3597, 3569, 2103, 2031, 3820, 957, 496, 1669, 1489, 1415, 705, 1508, 1932, 3021, 1329, 1551, 2638, 1169, 2620, 1564, 1809, 1112, 3667, 2626, 3759, 3331, 2481, 568, 3567, 304, 2593, 1351, 2323, 3010, 476, 1044, 1068, 665, 1053, 3002, 3610, 1463, 2537, 3805, 2878, 571, 211, 77, 3449, 3124, 1119, 3537, 1123, 1825, 3240, 83, 2766, 718, 3110, 103, 3390, 2886, 201, 984, 2650, 760, 2205, 2637, 3311, 3900, 2847, 3143, 324, 3073, 3711, 3218, 2756, 3906, 1322, 2727, 238, 1906, 2711, 1926, 1596, 3403, 1695, 753, 3520, 1859, 3913, 320, 2449, 619, 2894, 862, 2755, 746, 3673, 341, 2938, 1151, 2758, 447, 2635, 2992, 443, 1529, 1114, 685, 202, 850, 3843, 1755, 1613, 250, 2131, 1902, 3559, 600, 3222, 3587, 40, 2482, 2849, 386, 3612, 3223, 1928, 1152, 3797, 1844, 3221, 3122, 241, 1312, 484, 2778, 183, 295, 418, 3781, 2086, 3400, 3580, 2813, 2579, 3540, 583, 824, 263, 2666, 997, 1696, 2945, 38, 3586, 297, 462, 3934, 3319, 214, 2864, 3761, 716, 2896, 2577, 2493, 3845, 2853, 1585, 3942, 220, 2339, 49, 702, 3338, 2196, 3938, 722, 3931, 1477, 2494, 2559, 2426, 1874, 1583, 3329, 3531, 1490, 3665, 3939, 3573, 3562, 3885, 554, 1767, 1572, 2674, 3568, 184, 3924, 1063, 1880, 2441, 2187, 3830, 3349, 2483, 2586, 659, 3847, 392, 3106, 3171, 2293, 1814, 2785, 2678, 2305, 2128, 2767, 1328, 1496, 841, 2743, 1458, 767, 877, 3473, 1679, 274, 867, 2256, 3902, 3309, 1533, 3776, 1406, 3874, 1857, 478, 3721, 430, 1511, 3192, 3756, 3306, 2737, 3415, 961, 1325, 1426, 3345, 669, 3402, 298, 2843, 148, 3935, 1067, 1570, 967, 2397, 570, 1725, 1076, 219, 1324, 2800, 2047, 1421, 3941, 1671, 1728, 1879, 2873, 1455, 2715, 3749, 3488, 525, 3162, 331, 1822, 2227, 1509, 573, 2189, 3670, 3532, 3832, 2074, 84, 1437, 2837, 1893, 3894, 1335, 1933, 287, 876, 1846, 2164, 1632, 1692, 1000, 992, 3344, 2897, 2865, 1662, 831, 2292, 645, 960, 2691, 3854, 2809, 2201, 3637, 2158, 3464, 3313, 1666, 3848, 633, 3775, 3092, 389, 1412, 3862, 1657, 2157, 1163, 3161, 1494, 2512, 336, 2350, 1549, 626, 2211, 2452, 1055, 178, 638, 359, 3585, 1770, 283, 1168, 3880, 251, 146, 3047, 771, 3645, 2834, 3121, 394, 2509, 2544, 3465, 2056, 1501, 1087, 2175, 563, 3757, 2185, 2257, 617, 2534, 2904, 1493, 3574, 197, 1170, 3644, 375, 1116, 3139, 2923, 1853, 1807, 2963, 1651, 2740, 3490, 1565, 2913, 131, 649, 1990, 3625, 1504, 3137, 3933, 974, 3333, 3050, 3860, 3817, 3474, 1144, 2981, 2101, 1520, 3611, 189, 1154, 3283, 3940, 1574, 2415, 2388, 2008, 681, 3374, 751, 2298, 1989, 3351, 3883, 1423, 1898, 1450, 3025, 1349, 2627, 3492, 2824, 2773, 3581, 212, 2775, 1656, 2246, 2079, 567, 1153, 1575, 124, 807, 137, 119, 3419, 566, 228, 958, 2776, 96, 1313, 3850, 1121, 2768, 129, 1811, 2636, 3563, 503, 2998, 632, 2466, 1793, 3796, 3853, 411, 754, 1850, 561, 1502, 1715, 3642, 1117, 3058, 769, 3437, 3640, 200, 128, 3878, 2892, 2964, 3867, 106, 864, 1817, 2754, 2326, 3335, 3495, 75, 2545, 397, 2215, 925, 1878, 1539, 2197, 2281, 1058, 3116, 245, 1531, 962, 1383, 2830, 2695, 2342, 2658, 939, 2632, 2854, 1864, 2221, 1743, 2914, 3215, 114, 3777, 1675, 1038, 793, 2994, 860, 1872, 3012, 3570, 2675, 385, 2962, 3282, 244, 3463, 2209, 2191, 3892, 1899, 1181, 3486, 863, 2855, 703, 2839, 2219, 243, 2783, 2931, 1749, 2933, 2562, 1436, 2486, 755, 993, 3410, 775, 2984, 3648, 56, 726, 2156, 811, 652, 3803, 3636, 2569, 1891, 3149, 3944, 2503, 3140, 1567, 618, 614, 3003, 3154, 3905, 3026, 2129, 136, 3641, 2200, 1780, 526, 53, 3523, 2464, 1782, 1002, 2063, 874, 664, 598, 2207, 2831, 59, 1444, 2332, 854, 2234, 1026, 2814, 2317, 406, 3592, 37, 560, 3818, 3533, 1890, 2765, 1420, 1486, 847, 1718, 630, 1849, 2192, 3027, 1311, 1138, 1522, 1543, 108, 2705, 2304, 1514, 1720, 2760, 1659, 2061, 3891, 2487, 2911, 2244, 2673, 2850, 844, 3056, 1519, 732, 3778, 1903, 1538, 98, 966, 1532, 3866, 3166, 1384, 2602, 90, 3666, 2833, 972, 1534, 3303, 310, 815, 3657, 2242, 1685, 1160, 3292, 3001, 264, 2934, 2233, 1664, 3245, 3875, 3232, 1636, 2444, 1164, 698, 1741, 2608, 2557, 1471, 1796, 3652, 1622, 980, 167, 1040, 559, 3207, 3293, 3346, 1930, 1174, 2631, 2538, 2930, 2777, 1098, 1369, 3443, 3184, 2679, 1433, 1901, 1071]

In [87]:
# Filter to keep only rows where the 'item' is in your list
filtered_df = ratings_df[ratings_df["item"].isin(filtered_movies_list)]

filtered_df

         user  item  rating         ts
0           1  1193       5  978300760
1           1   661       3  978302109
2           1   914       3  978301968
3           1  3408       4  978300275
4           1  2355       5  978824291
...       ...   ...     ...        ...
1000204  6040  1091       1  956716541
1000205  6040  1094       5  956704887
1000206  6040   562       5  956704746
1000207  6040  1096       4  956715648
1000208  6040  1097       4  956715569

[999611 rows x 4 columns]

In [88]:
print(filtered_df["user"].nunique())
print(filtered_df["item"].nunique())

6040
3416

## 3.2 Re-index movie and user ID

number users starting from 0, and movies starting from 1. movie_id 0 is reserved as a padding value, not a real movie. padding will be used later, where a user's history list is filled with movie_id up to a fixed length, and if a user watches less movie than the length of the list, the rest will be filled with 0. since no movie has movie_id=0, the 0 in the list would not be confused with a movie

In [89]:
item_ids = np.sort(filtered_df["item"].unique())
item_map = {i: k + 1 for k, i in enumerate(item_ids)} 

user_ids = np.sort(filtered_df["user"].unique())
user_map = {i: k for k, i in enumerate(user_ids)}

filtered_df["movie_id"] = filtered_df["item"].map(item_map)
filtered_df["user_id"] = filtered_df["user"].map(user_map)

filtered_df = filtered_df.sort_values(by=["user", "ts"])
filtered_df

         user  item  rating         ts  movie_id  user_id
31          1  3186       4  978300019      2758        0
22          1  1270       5  978300055      1069        0
27          1  1721       4  978300055      1445        0
37          1  1022       5  978300055       862        0
24          1  2340       3  978300103      1979        0
...       ...   ...     ...        ...       ...      ...
1000019  6040  2917       4  997454429      2513     6039
999988   6040  1921       4  997454464      1591     6039
1000172  6040  1784       3  997454464      1486     6039
1000167  6040   161       3  997454486       146     6039
1000042  6040  1221       4  998315055      1022     6039

[999611 rows x 6 columns]

## 3.3 Splitting data

In [90]:
train_df = filtered_df.groupby("user", group_keys=False).apply(
    lambda x: x.iloc[:-2]
)
train_df

         user  item  rating         ts  movie_id  user_id
31          1  3186       4  978300019      2758        0
22          1  1270       5  978300055      1069        0
27          1  1721       4  978300055      1445        0
37          1  1022       5  978300055       862        0
24          1  2340       3  978300103      1979        0
...       ...   ...     ...        ...       ...      ...
1000119  6040  3671       4  997454367      3156     6039
999923   6040   232       5  997454398       214     6039
1000019  6040  2917       4  997454429      2513     6039
999988   6040  1921       4  997454464      1591     6039
1000172  6040  1784       3  997454464      1486     6039

[987531 rows x 6 columns]

In [91]:
val_df = filtered_df.groupby("user", group_keys=False).apply(
    lambda x: x.iloc[-2:-1]
)
val_df

         user  item  rating         ts  movie_id  user_id
34          1  1907       4  978824330      1579        0
87          2  1544       4  978300174      1301        1
191         3  3868       3  978298486      3340        2
237         4  1036       4  978294282       876        3
418         5  1884       3  978246576      1558        4
...       ...   ...     ...        ...       ...      ...
999076   6036  3574       1  956755196      3075     6035
999557   6037   968       4  956801840       817     6036
999741   6038  2700       1  956715051      2310     6037
999815   6039  1204       5  956758029      1005     6038
1000167  6040   161       3  997454486       146     6039

[6040 rows x 6 columns]

In [92]:
test_df = filtered_df.groupby("user", group_keys=False).apply(
    lambda x: x.iloc[-1:]
)
test_df

         user  item  rating         ts  movie_id  user_id
25          1    48       5  978824351        47        0
136         2  1917       3  978300174      1587        1
232         3  2081       4  978298504      1749        2
243         4  1954       5  978294282      1624        3
258         5   288       2  978246585       267        4
...       ...   ...     ...        ...       ...      ...
999251   6036  2643       1  956755196      2257     6035
999684   6037   435       3  956801840       403     6036
999731   6038  1183       5  956717204       985     6037
999826   6039  1254       4  956758029      1053     6038
1000042  6040  1221       4  998315055      1022     6039

[6040 rows x 6 columns]

## 3.4 Data transformation

plot a matrix where every row is one user_id, and every column is one movie_id. if the user watched the movie, put a 1 under the movie_id, else 0

In [93]:
import scipy.sparse as sp

num_users = filtered_df["user"].nunique()
num_items = filtered_df["item"].nunique()

train_matrix = sp.csr_matrix(
    (np.ones(len(train_df), dtype=np.float32), (train_df["user_id"].to_numpy(), train_df["movie_id"].to_numpy())),
    shape=(num_users, num_items + 1)
)  

print(train_matrix[65:85, 325:345].toarray())
print("Shape:", train_matrix.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Shape: (6040, 3417)

# 4. Model

## 4.1 Popularity model

In [94]:
# prints a list, where the first item is the padding slot, 
# then second item is movie_id 1, which was watched by 2064 users

item_popularity = np.asarray(train_matrix.sum(0)).ravel()
print(item_popularity[:10])

[   0. 2064.  695.  468.  170.  292.  935.  457.   68.  102.]

In [95]:
val_item  = val_df["movie_id"].to_numpy()
print(val_item)

[1579 1301 3340 ... 2310 1005  146]

In [96]:
val_matrix = sp.csr_matrix(
    (np.ones(len(val_df), dtype=np.float32), (val_df["user_id"].to_numpy(), val_df["movie_id"].to_numpy())),
    shape=(num_users, num_items + 1)
)

seen = train_matrix + val_matrix
print(seen[65:85, 325:345].toarray())

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [97]:
# give the same score to all users, 
# resulting in a table with 6040 rows (one row per user) and 3417 columns (one per movie), 
# where every row is the same  

popularity_scores = np.tile(item_popularity, (num_users, 1))
print(popularity_scores.shape)
print(popularity_scores)

(6040, 3417)
[[   0. 2064.  695. ...   52.   39.  372.]
 [   0. 2064.  695. ...   52.   39.  372.]
 [   0. 2064.  695. ...   52.   39.  372.]
 ...
 [   0. 2064.  695. ...   52.   39.  372.]
 [   0. 2064.  695. ...   52.   39.  372.]
 [   0. 2064.  695. ...   52.   39.  372.]]

In [98]:
# give every watched movie the worst score (negative infinity), 
# so that it wouldn't be recommended 

popularity_scores = popularity_scores.astype(np.float64)

# turn padding column into -inf also so it won't be recommended
popularity_scores[:, 0] = -np.inf            

rows, cols = seen.nonzero()                 
popularity_scores[rows, cols] = -np.inf
print(popularity_scores)

[[ -inf  -inf  695. ...   52.   39.  372.]
 [ -inf 2064.  695. ...   52.   39.  372.]
 [ -inf 2064.  695. ...   52.   39.  372.]
 ...
 [ -inf 2064.  695. ...   52.   39.  372.]
 [ -inf 2064.  695. ...   52.   39.  372.]
 [ -inf  -inf  695. ...   52.   39.  372.]]

In [99]:
popularity_scores_df = test_df.copy() 

test_scores = []
for _, row in test_df.iterrows():                 
    u = row["user_id"]                               
    i = row["movie_id"]                        
    test_scores.append(popularity_scores[u, i])       

popularity_scores_df["score"] = test_scores
popularity_scores_df = popularity_scores_df[["user_id", "movie_id", "score"]] 
popularity_scores_df

         user_id  movie_id   score
25             0        47   372.0
136            1      1587  1102.0
232            2      1749  1025.0
243            3      1624  1116.0
258            4       267   694.0
...          ...       ...     ...
999251      6035      2257   316.0
999684      6036       403   531.0
999731      6037       985   976.0
999826      6038      1053   452.0
1000042     6039      1022  1674.0

[6040 rows x 3 columns]

In [100]:
test_ranks = []
for _, row in popularity_scores_df.iterrows(): 
    u = int(row["user_id"])                              
    s = row["score"] 
    test_ranks.append((popularity_scores[u] > s).sum())

# rank shows how many movies have a score higher itself
popularity_scores_df["rank"] = test_ranks
popularity_scores_df

         user_id  movie_id   score  rank
25             0        47   372.0   802
136            1      1587  1102.0   119
232            2      1749  1025.0   165
243            3      1624  1116.0   138
258            4       267   694.0   312
...          ...       ...     ...   ...
999251      6035      2257   316.0   457
999684      6036       403   531.0   450
999731      6037       985   976.0   205
999826      6038      1053   452.0   623
1000042     6039      1022  1674.0    12

[6040 rows x 4 columns]

In [101]:
sample_df = popularity_scores_df.copy()
sample_df["recall@20"] = sample_df["rank"] < 20

sample_df["ndcg@20"] = np.where(
    sample_df["rank"] < 20,
    1 / np.log2(sample_df["rank"] + 2),
    0.0,
)

sample_df

         user_id  movie_id   score  rank  recall@20  ndcg@20
25             0        47   372.0   802      False  0.00000
136            1      1587  1102.0   119      False  0.00000
232            2      1749  1025.0   165      False  0.00000
243            3      1624  1116.0   138      False  0.00000
258            4       267   694.0   312      False  0.00000
...          ...       ...     ...   ...        ...      ...
999251      6035      2257   316.0   457      False  0.00000
999684      6036       403   531.0   450      False  0.00000
999731      6037       985   976.0   205      False  0.00000
999826      6038      1053   452.0   623      False  0.00000
1000042     6039      1022  1674.0    12       True  0.26265

[6040 rows x 6 columns]

In [102]:
# look at each user's top K recommendations, 
# if the ranking falls within the top K, true, else false
# find the mean number of times true happens, this is known as Recall@K 

# NDCG is a score that rewards getting the right movie higher in the list (closer to 0), 
# not just any position in the top K 

# for recall and NDCG, both run from 0 to 1, higher is better

def score_model(df, k):     
    recall = (df < k).mean()
    print(f"Recall@{k}:", recall)

    ndcg = np.where(df < k, 1 / np.log2(df + 2), 0).mean()
    print(f"NDCG@{k}:", ndcg)

In [103]:
popularity_ranks = popularity_scores_df["rank"].to_numpy()
K = [10,20]
for k in K: 
    score_model(popularity_ranks,k)

Recall@10: 0.0369205298013245
NDCG@10: 0.018032673467874877
Recall@20: 0.06837748344370861
NDCG@20: 0.025880026490064954

## 4.2 Item-KNN

In [104]:
# co-occurrence: result is a movie × movie table, 
# where each entry counts how many users watched both movies

co = (train_matrix.T @ train_matrix).toarray()

print(co.shape)
print(co[:10, :10])

(3417, 3417)
[[   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0. 2064.  488.  286.  112.  212.  511.  313.   51.   58.]
 [   0.  488.  695.  151.   54.  118.  230.  163.   43.   49.]
 [   0.  286.  151.  468.   62.  122.  149.  153.   19.   35.]
 [   0.  112.   54.   62.  170.   66.   61.   69.    7.   13.]
 [   0.  212.  118.  122.   66.  292.   93.  121.   14.   30.]
 [   0.  511.  230.  149.   61.   93.  935.  142.   16.   61.]
 [   0.  313.  163.  153.   69.  121.  142.  457.   11.   25.]
 [   0.   51.   43.   19.    7.   14.   16.   11.   68.    6.]
 [   0.   58.   49.   35.   13.   30.   61.   25.    6.  102.]]

In [105]:
# turn raw counts into similarity score, as raw count only shows 
# the number of people who watched both movies, but does not take into account 
# audience size. also need to apply a shrinkage factor, so that movies watched 
# only by 1 person dont have a perfect score (due to the math of cosine similarity)

co_noself = co.copy()
np.fill_diagonal(co_noself, 0)    
print(co_noself[:10, :10])

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0. 488. 286. 112. 212. 511. 313.  51.  58.]
 [  0. 488.   0. 151.  54. 118. 230. 163.  43.  49.]
 [  0. 286. 151.   0.  62. 122. 149. 153.  19.  35.]
 [  0. 112.  54.  62.   0.  66.  61.  69.   7.  13.]
 [  0. 212. 118. 122.  66.   0.  93. 121.  14.  30.]
 [  0. 511. 230. 149.  61.  93.   0. 142.  16.  61.]
 [  0. 313. 163. 153.  69. 121. 142.   0.  11.  25.]
 [  0.  51.  43.  19.   7.  14.  16.  11.   0.   6.]
 [  0.  58.  49.  35.  13.  30.  61.  25.   6.   0.]]

In [106]:
# similarity(a, b) = shared / (sqrt(popularity a) × sqrt(popularity b) + shrinkage)
# eg. 0.404 is the similarity score between movie 1 and 2 == score between movie 2 and 1
# values around 0.2 to 0.4 are strong links between popular movies.
# movie 1 is most similar to movies 6 and 2 (0.365 and 0.404) 
# and least to 9 and 8 (0.124 and 0.133). 
# if someone has watched movie 1, then movies 2 and 6 will get the 
# biggest boosts in their recommendations.

shrink = 10.0           

normalized_popularity = np.sqrt(item_popularity)
print("Pre-normalisation:",item_popularity)
print("Post-normalisation:", normalized_popularity.round(1))

S = co_noself / (np.outer(normalized_popularity, normalized_popularity) + shrink)
print(S[:10, :10].round(3))

Pre-normalisation: [   0. 2064.  695. ...   52.   39.  372.]
Post-normalisation: [ 0.  45.4 26.4 ...  7.2  6.2 19.3]
[[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.404 0.288 0.186 0.27  0.365 0.319 0.133 0.124]
 [0.    0.404 0.    0.26  0.153 0.256 0.282 0.284 0.189 0.177]
 [0.    0.288 0.26  0.    0.212 0.321 0.222 0.324 0.101 0.153]
 [0.    0.186 0.153 0.212 0.    0.284 0.149 0.239 0.06  0.092]
 [0.    0.27  0.256 0.321 0.284 0.    0.175 0.322 0.093 0.164]
 [0.    0.365 0.282 0.222 0.149 0.175 0.    0.214 0.061 0.191]
 [0.    0.319 0.284 0.324 0.239 0.322 0.214 0.    0.059 0.111]
 [0.    0.133 0.189 0.101 0.06  0.093 0.061 0.059 0.    0.064]
 [0.    0.124 0.177 0.153 0.092 0.164 0.191 0.111 0.064 0.   ]]

In [107]:
# for each movie, keep only its top-k most similar neighbours and 
# set all its other similarities to 0.
# most of the 3,417 similarities in each row are tiny and come from a few 
# random shared viewers. adding up hundreds of tiny noisy values for every 
# watched movie drowns out the strong links.
# k is a setting we tune on the validation set
# each row in S_k is a movie, and the values is how much similarity the movie 
# gives to another movie, eg S_k[4,5] means movie 4 gives movie 5 a similarity of 0.284

k = 100

num_rows = S.shape[0]
S_k = S.copy()           

for row in range(1, num_rows):
    movie_row = S_k[row]
    sorted_row = sorted(movie_row, reverse=True)
    threshold = sorted_row[k - 1]

    S_k[row] = np.where(movie_row >= threshold, movie_row, 0)

print("Shape:", S_k.shape)
print(S_k[:10, :10].round(3))
print("----------------------------------")
print(train_matrix[:10, :10].toarray())

Shape: (3417, 3417)
[[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.404 0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.321 0.    0.324 0.    0.   ]
 [0.    0.    0.    0.    0.    0.284 0.    0.239 0.    0.   ]
 [0.    0.    0.    0.321 0.    0.    0.    0.322 0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.189 0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]]
----------------------------------
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0. 0.]]

In [108]:
# scores are calculated for the movies that a user hasn't watched yet, 
# which is equal to the sum of the similarity values from other movies
# eg, user 0's history = [0, 1, 0, 1, 0], which means they watched movies 1 & 3
# goal is to calculate the score for movies 2 & 4, which they haven't yet watched
# row*col multiplication gives the sum of the similarity scores that a movie receives 
# from the movies that the user has watched
# every row is one user

scores_knn = train_matrix @ S_k
print(scores_knn[:10, :10].round(3))

[[ 0.    18.079  3.129  0.     0.     0.     0.82   0.313  0.     0.   ]
 [ 0.    20.093  0.44   0.     0.     0.    16.43   0.32   0.     0.   ]
 [ 0.    15.198  1.555  0.     0.     0.     2.796  0.     0.     0.   ]
 [ 0.     5.96   0.     0.     0.     0.     1.25   0.     0.     0.   ]
 [ 0.    29.661  0.118  0.     0.098  0.    16.769  0.764  0.     0.   ]
 [ 0.    12.551  3.239  0.     0.269  0.854  1.418  2.512  0.     0.   ]
 [ 0.     8.458  0.     0.     0.     0.     8.657  0.     0.     0.   ]
 [ 0.    16.71   0.649  0.331  1.197  0.284 16.122  3.117  0.     0.236]
 [ 0.    28.578  0.     0.331  0.     0.    11.547  1.285  0.     0.   ]
 [ 0.    68.229 19.206  3.005  0.553  6.239  5.233  9.273  0.169  0.   ]]

In [109]:
# turn the movies that a user has already watched into score = -inf 
# so it won't be recommended 

scores = np.asarray(scores_knn, dtype=np.float64)
rows, cols = train_matrix.nonzero()                 
scores[rows, cols] = -np.inf

scores[:, 0] = -np.inf 

print(scores[:10, :10].round(3))

[[  -inf   -inf  3.129  0.     0.     0.     0.82   0.313  0.     0.   ]
 [  -inf 20.093  0.44   0.     0.     0.    16.43   0.32   0.     0.   ]
 [  -inf 15.198  1.555  0.     0.     0.     2.796  0.     0.     0.   ]
 [  -inf  5.96   0.     0.     0.     0.     1.25   0.     0.     0.   ]
 [  -inf 29.661  0.118  0.     0.098  0.      -inf  0.764  0.     0.   ]
 [  -inf   -inf  3.239  0.     0.269  0.854  1.418  2.512  0.     0.   ]
 [  -inf  8.458  0.     0.     0.     0.      -inf  0.     0.     0.   ]
 [  -inf   -inf  0.649  0.331   -inf  0.284 16.122  3.117  0.     0.236]
 [  -inf   -inf  0.     0.331  0.     0.    11.547  1.285  0.     0.   ]
 [  -inf   -inf   -inf  3.005  0.553  6.239  5.233   -inf  0.169  0.   ]]

In [110]:
knn_scores_df = val_df.copy() 

val_scores = []
for _, row in val_df.iterrows():                 
    u = row["user_id"]                               
    i = row["movie_id"]                        
    val_scores.append(scores[u, i])       

knn_scores_df["score"] = val_scores
knn_scores_df = knn_scores_df[["user_id", "movie_id", "score"]] 
knn_scores_df

         user_id  movie_id      score
34             0      1579   5.798222
87             1      1301  19.222279
191            2      3340   0.000000
237            3       876   9.814115
418            4      1558   1.779697
...          ...       ...        ...
999076      6035      3075   0.422762
999557      6036       817   3.560987
999741      6037      2310   1.091273
999815      6038      1005  12.025081
1000167     6039       146   1.866388

[6040 rows x 3 columns]

In [111]:
val_ranks = []
for _, row in knn_scores_df.iterrows(): 
    u = int(row["user_id"])                              
    s = row["score"] 
    val_ranks.append((scores[u] > s).sum())

# rank shows how many movies have a score higher itself
knn_scores_df["rank"] = val_ranks
knn_scores_df

         user_id  movie_id      score  rank
34             0      1579   5.798222    91
87             1      1301  19.222279    37
191            2      3340   0.000000   701
237            3       876   9.814115     3
418            4      1558   1.779697   479
...          ...       ...        ...   ...
999076      6035      3075   0.422762  1360
999557      6036       817   3.560987   291
999741      6037      2310   1.091273   183
999815      6038      1005  12.025081    68
1000167     6039       146   1.866388   562

[6040 rows x 4 columns]

In [112]:
count = 0 
testtttt = scores[27]
for score in testtttt:
    if score > 26.014493942260742:
        count+=1 

print(count)

12

In [116]:
knn_scores = knn_scores_df["rank"].to_numpy()
K = [10,20]
for k in K: 
    score_model(knn_scores,k)

Recall@10: 0.06390728476821192
NDCG@10: 0.032862614573288554
Recall@20: 0.10430463576158941
NDCG@20: 0.043018531584930866

tune k, then keep the best validation

In [119]:
def knn_val_rank(k):
    print(f"Item-KNN for top {k} values")
    num_rows = S.shape[0]
    S_k = S.copy()           

    for row in range(1, num_rows):
        movie_row = S_k[row]
        sorted_row = sorted(movie_row, reverse=True)
        threshold = sorted_row[k - 1]

        S_k[row] = np.where(movie_row >= threshold, movie_row, 0)

    scores_knn = train_matrix @ S_k
    scores = np.asarray(scores_knn, dtype=np.float64)
    rows, cols = train_matrix.nonzero()                 
    scores[rows, cols] = -np.inf

    scores[:, 0] = -np.inf 

    knn_scores_df = val_df.copy() 

    val_scores = []
    for _, row in val_df.iterrows():                 
        u = row["user_id"]                               
        i = row["movie_id"]                        
        val_scores.append(scores[u, i])       

    knn_scores_df["score"] = val_scores
    knn_scores_df = knn_scores_df[["user_id", "movie_id", "score"]] 

    val_ranks = []
    for _, row in knn_scores_df.iterrows(): 
        u = int(row["user_id"])                              
        s = row["score"] 
        val_ranks.append((scores[u] > s).sum())

    # rank shows how many movies have a score higher itself
    knn_scores_df["rank"] = val_ranks

    knn_scores = knn_scores_df["rank"].to_numpy()
    K = [10,20]
    for top_k in K: 
        score_model(knn_scores,top_k)

    print("=================================")

In [120]:
k_values = [50,100,150,200]
for k in k_values: 
    knn_val_rank(k)

Item-KNN for top 50 values
Recall@10: 0.06804635761589405
NDCG@10: 0.03448194849586907
Recall@20: 0.11572847682119206
NDCG@20: 0.04643956667393202
=================================
Item-KNN for top 100 values
Recall@10: 0.06390728476821192
NDCG@10: 0.032862614573288554
Recall@20: 0.10430463576158941
NDCG@20: 0.043018531584930866
=================================
Item-KNN for top 150 values
Recall@10: 0.06407284768211921
NDCG@10: 0.03305385552788082
Recall@20: 0.09983443708609271
NDCG@20: 0.04199704118491187
=================================
Item-KNN for top 200 values
Recall@10: 0.06175496688741722
NDCG@10: 0.031457825463457094
Recall@20: 0.09635761589403974
NDCG@20: 0.040097259176664624
=================================

In [124]:
new_k_values = [4,5,10,20,30,40,50]
for k in new_k_values: 
    knn_val_rank(k)

Item-KNN for top 4 values
Recall@10: 0.07897350993377483
NDCG@10: 0.03898757339890384
Recall@20: 0.13129139072847681
NDCG@20: 0.052103122057356614
=================================
Item-KNN for top 5 values
Recall@10: 0.08327814569536424
NDCG@10: 0.04025731670344227
Recall@20: 0.13625827814569536
NDCG@20: 0.05354895164621536
=================================
Item-KNN for top 10 values
Recall@10: 0.08129139072847683
NDCG@10: 0.03900455291875239
Recall@20: 0.13228476821192053
NDCG@20: 0.05177405939395147
=================================
Item-KNN for top 20 values
Recall@10: 0.0759933774834437
NDCG@10: 0.036219986294728126
Recall@20: 0.12549668874172185
NDCG@20: 0.04858955052710694
=================================
Item-KNN for top 30 values
Recall@10: 0.07019867549668875
NDCG@10: 0.03474205120043414
Recall@20: 0.12102649006622516
NDCG@20: 0.047461088232064526
=================================
Item-KNN for top 40 values
Recall@10: 0.06937086092715232
NDCG@10: 0.035628835813540434
Recall@20: 0.1173841059602649
NDCG@20: 0.04767010005625954
=================================
Item-KNN for top 50 values
Recall@10: 0.06804635761589405
NDCG@10: 0.03448194849586907
Recall@20: 0.11572847682119206
NDCG@20: 0.04643956667393202
=================================

In [ ]:
k = 5

num_rows = S.shape[0]
S_k = S.copy()           

for row in range(1, num_rows):
    movie_row = S_k[row]
    sorted_row = sorted(movie_row, reverse=True)
    threshold = sorted_row[k - 1]

    S_k[row] = np.where(movie_row >= threshold, movie_row, 0)

scores_test = np.asarray(seen @ S_k, dtype=np.float64)
rows, cols = seen.nonzero()                 
scores_test[rows, cols] = -np.inf

scores_test[:, 0] = -np.inf 

knn_scores_test_df = test_df.copy() 

test_scores = []
for _, row in test_df.iterrows():                 
    u = row["user_id"]                               
    i = row["movie_id"]                        
    test_scores.append(scores_test[u, i])       

knn_scores_test_df["score"] = test_scores
knn_scores_test_df = knn_scores_test_df[["user_id", "movie_id", "score"]] 

test_ranks = []
for _, row in knn_scores_test_df.iterrows(): 
    u = int(row["user_id"])                              
    s = row["score"] 
    test_ranks.append((scores_test[u] > s).sum())

# rank shows how many movies have a score higher itself
knn_scores_test_df["rank"] = test_ranks

knn_scores_test = knn_scores_test_df["rank"].to_numpy()
K = [10,20]
for top_k in K: 
    score_model(knn_scores_test,top_k)

Recall@10: 0.08178807947019867
NDCG@10: 0.04019327588633563
Recall@20: 0.13278145695364238
NDCG@20: 0.05300273581529803